import { createReadStream, existsSync, statSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { extname, join, normalize } from 'node:path';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { db, upsertLead, addEvent, scheduleAutomations } from './lib/database.mjs';
import { processDueMessages } from './lib/automation.mjs';
import { getProduct } from './lib/products.mjs';
import { chargeOpaque, chargeProfile } from './lib/authorize-net.mjs';

const root=process.cwd(),port=Number(process.env.PORT||4173),now=()=>new Date().toISOString();
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const json=(res,status,value)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(value));};
const secureEqual=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&timingSafeEqual(x,y)};
const adminOk=req=>{const[kind,token='']=(req.headers.authorization||'').split(' ');if(kind!=='Basic')return false;const[user,password]=Buffer.from(token,'base64').toString().split(':');return secureEqual(user,process.env.ADMIN_USER||'admin')&&secureEqual(password,process.env.ADMIN_PASSWORD||'change-me')};
const requireAdmin=(req,res)=>{if(adminOk(req))return true;res.writeHead(401,{'www-authenticate':'Basic realm="WifiCode Admin"'});res.end('Authentication required');return false};
const sessionSecret=()=>process.env.SESSION_SECRET||'';
const sign=value=>createHmac('sha256',sessionSecret()).update(value).digest('base64url');
const makeSession=leadId=>{const value=Buffer.from(JSON.stringify({leadId:Number(leadId),created:Date.now()})).toString('base64url');return `${value}.${sign(value)}`};
const readSession=req=>{try{const cookie=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('wc_session='));if(!cookie||!sessionSecret())return null;const token=decodeURIComponent(cookie.slice(11)),[value,signature]=token.split('.');if(!secureEqual(signature,sign(value)))return null;const session=JSON.parse(Buffer.from(value,'base64url').toString());return Date.now()-session.created<86400000?session:null}catch{return null}};
const setSession=(req,res,leadId)=>{const secure=(req.headers['x-forwarded-proto']==='https'||process.env.APP_URL?.startsWith('https://'))?'; Secure':'';res.setHeader('set-cookie',`wc_session=${encodeURIComponent(makeSession(leadId))}; Path=/; HttpOnly; SameSite=Lax; Max-Age=86400${secure}`)};

async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>1e6)throw Error('Request too large');chunks.push(chunk)}const raw=Buffer.concat(chunks).toString(),type=req.headers['content-type']||'';return type.includes('application/json')?(raw?JSON.parse(raw):{}):Object.fromEntries(new URLSearchParams(raw))}
function stream(file,res){if(!existsSync(file)){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':types[extname(file).toLowerCase()]||'application/octet-stream','cache-control':'no-cache'});createReadStream(file).pipe(res)}

async function api(req,res,url){
  if(req.method==='GET'&&url.pathname==='/api/checkout/config'){try{const product=getProduct(url.searchParams.get('product')||'front');return json(res,200,{apiLoginId:process.env.AUTHORIZE_NET_API_LOGIN_ID,publicClientKey:process.env.AUTHORIZE_NET_PUBLIC_CLIENT_KEY,environment:process.env.AUTHORIZE_NET_ENV,product:{id:product.id,name:product.name,formatted:`$${product.amount.toFixed(2)}`}})}catch(error){return json(res,400,{error:error.message})}}
  if(req.method==='POST'&&url.pathname==='/api/checkout'){const input=await body(req);if(!input.consent)return json(res,400,{error:'Payment authorization is required'});let product;try{product=getProduct(input.product)}catch(error){return json(res,400,{error:error.message})}if(product.id!=='front')return json(res,400,{error:'Initial checkout product is invalid'});const result=upsertLead({...input,source:'checkout',email_consent:false,sms_consent:false});const lead=result.lead;let order=db.prepare('SELECT * FROM orders WHERE lead_id=? AND product_id=?').get(lead.id,product.id);if(order?.status==='paid'){setSession(req,res,lead.id);return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)})}const stamp=now();if(order){db.prepare("UPDATE orders SET status='pending',response_message='',updated_at=? WHERE id=?").run(stamp,order.id)}else{const inserted=db.prepare('INSERT INTO orders(lead_id,product_id,product_name,amount,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(lead.id,product.id,product.name,product.amount,'pending',stamp,stamp);order={id:inserted.lastInsertRowid}}try{const payment=await chargeOpaque({product,opaqueData:input.opaqueData,customer:input,invoice:`WC-${order.id}`});db.prepare("UPDATE orders SET status='paid',transaction_id=?,response_code=?,response_message='Approved',updated_at=? WHERE id=?").run(payment.transactionId,payment.responseCode,now(),order.id);if(payment.customerProfileId&&payment.paymentProfileId)db.prepare(`INSERT INTO gateway_profiles(lead_id,customer_profile_id,payment_profile_id,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(lead_id) DO UPDATE SET customer_profile_id=excluded.customer_profile_id,payment_profile_id=excluded.payment_profile_id,updated_at=excluded.updated_at`).run(lead.id,payment.customerProfileId,payment.paymentProfileId,now(),now());addEvent(lead.id,'sale',{value:product.amount,currency:'USD',product_id:product.id,transaction_id:payment.transactionId,metadata:{gateway:'authorize_net'}});scheduleAutomations(lead,'conversion');setSession(req,res,lead.id);return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)})}catch(error){db.prepare("UPDATE orders SET status='declined',response_code=?,response_message=?,updated_at=? WHERE id=?").run(error.code||'',String(error.message).slice(0,500),now(),order.id);return json(res,402,{error:error.message})}}
  if(req.method==='POST'&&url.pathname==='/api/purchase'){const session=readSession(req);if(!session)return json(res,401,{error:'Your secure checkout session expired. Please complete the initial checkout again.'});const input=await body(req);let product;try{product=getProduct(input.product)}catch(error){return json(res,400,{error:error.message})}if(product.id==='front')return json(res,400,{error:'Invalid upgrade'});const lead=db.prepare('SELECT * FROM leads WHERE id=?').get(session.leadId),profile=db.prepare('SELECT * FROM gateway_profiles WHERE lead_id=?').get(session.leadId);if(!lead||!profile)return json(res,409,{error:'Saved payment profile is unavailable. Please contact support.'});let order=db.prepare('SELECT * FROM orders WHERE lead_id=? AND product_id=?').get(lead.id,product.id);if(order?.status==='paid')return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)});const stamp=now();if(order){db.prepare("UPDATE orders SET status='pending',response_message='',updated_at=? WHERE id=?").run(stamp,order.id)}else{const inserted=db.prepare('INSERT INTO orders(lead_id,product_id,product_name,amount,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(lead.id,product.id,product.name,product.amount,'pending',stamp,stamp);order={id:inserted.lastInsertRowid}}try{const payment=await chargeProfile({product,customerProfileId:profile.customer_profile_id,paymentProfileId:profile.payment_profile_id,invoice:`WC-${order.id}`});db.prepare("UPDATE orders SET status='paid',transaction_id=?,response_code=?,response_message='Approved',updated_at=? WHERE id=?").run(payment.transactionId,payment.responseCode,now(),order.id);addEvent(lead.id,'sale',{value:product.amount,currency:'USD',product_id:product.id,transaction_id:payment.transactionId,metadata:{gateway:'authorize_net',one_click:true}});return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)})}catch(error){db.prepare("UPDATE orders SET status='declined',response_code=?,response_message=?,updated_at=? WHERE id=?").run(error.code||'',String(error.message).slice(0,500),now(),order.id);return json(res,402,{error:error.message})}}
  if(req.method==='POST'&&url.pathname==='/api/leads'){const input=await body(req);input.ip=req.headers['x-forwarded-for']?.split(',')[0]||req.socket.remoteAddress||'';const result=upsertLead(input);addEvent(result.lead.id,'opt_in',{page:input.landing_page,metadata:{source:input.source||'website'}});if(result.created)scheduleAutomations(result.lead);return json(res,201,{ok:true,id:Number(result.lead.id)})}
  if(req.method==='POST'&&url.pathname==='/api/events'){const input=await body(req),allowed=new Set(['page_view','checkout_click']);if(!allowed.has(input.type))return json(res,400,{error:'Unsupported event'});addEvent(null,input.type,{page:input.page,product_id:input.product_id,metadata:{aid:input.aid,tid:input.tid,utm_source:input.utm_source,utm_campaign:input.utm_campaign}});return json(res,201,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/webhooks/jvzoo'){const supplied=url.searchParams.get('secret')||req.headers['x-webhook-secret'];if(!process.env.WEBHOOK_SECRET||!secureEqual(supplied,process.env.WEBHOOK_SECRET))return json(res,401,{error:'Invalid webhook secret'});const input=await body(req),email=input.ccustemail||input.email,name=input.ccustname||input.name||'';const result=upsertLead({email,phone:input.ccustphone||input.phone,name,source:'jvzoo',aid:input.caffitid||input.aid,tid:input.ctid||input.tid});const raw=String(input.ctransaction||input.transaction_type||input.type||'sale').toLowerCase(),eventType=raw.includes('refund')||raw.includes('cancel')?'refund':'sale';const added=addEvent(result.lead.id,eventType,{value:input.camount||input.amount||input.ctransamount,currency:input.ccurrency||'USD',product_id:input.cproditem||input.product_id,transaction_id:input.ctransreceipt||input.transaction_id,metadata:input});if(added&&eventType==='sale')scheduleAutomations(result.lead,'conversion');return json(res,200,{ok:true})}
  if(url.pathname.startsWith('/api/admin/')){if(!requireAdmin(req,res))return;
    if(req.method==='GET'&&url.pathname==='/api/admin/dashboard'){const leads=Number(db.prepare('SELECT COUNT(*) n FROM leads').get().n),conversions=Number(db.prepare("SELECT COUNT(*) n FROM events WHERE type='sale'").get().n),revenue=Number(db.prepare("SELECT COALESCE(SUM(value),0) n FROM events WHERE type='sale'").get().n);return json(res,200,{stats:{leads,conversions,revenue,rate:leads?((conversions/leads)*100).toFixed(1):'0.0'},leads:db.prepare('SELECT * FROM leads ORDER BY created_at DESC LIMIT 250').all(),conversions:db.prepare("SELECT e.*,l.email,l.phone FROM events e LEFT JOIN leads l ON l.id=e.lead_id WHERE e.type IN ('sale','refund') ORDER BY e.created_at DESC LIMIT 100").all(),automations:db.prepare('SELECT * FROM automations ORDER BY created_at DESC').all(),messages:db.prepare('SELECT * FROM messages ORDER BY created_at DESC LIMIT 100').all()})}
    if(req.method==='POST'&&url.pathname==='/api/admin/leads'){const input=await body(req);input.source='admin';const result=upsertLead(input);addEvent(result.lead.id,'opt_in',{metadata:{source:'admin'}});if(result.created)scheduleAutomations(result.lead);return json(res,201,{ok:true,id:Number(result.lead.id)})}
    if(req.method==='POST'&&url.pathname==='/api/admin/automations'){const input=await body(req);if(!['email','sms'].includes(input.channel))return json(res,400,{error:'Invalid channel'});const stamp=now();if(input.id)db.prepare('UPDATE automations SET name=?,channel=?,delay_minutes=?,subject=?,message=?,enabled=?,updated_at=? WHERE id=?').run(input.name,input.channel,Number(input.delay_minutes),input.subject||'',input.message,input.enabled?1:0,stamp,input.id);else db.prepare('INSERT INTO automations(name,channel,delay_minutes,subject,message,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(input.name,input.channel,Number(input.delay_minutes),input.subject||'',input.message,input.enabled?1:0,stamp,stamp);return json(res,201,{ok:true})}
  }
  return json(res,404,{error:'Not found'})
}

async function handler(req,res){try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(url.pathname==='/checkout')return stream(join(root,'public','checkout.html'),res);if(url.pathname==='/admin'||url.pathname==='/admin/'){if(!requireAdmin(req,res))return;return stream(join(root,'public','admin.html'),res)}if(url.pathname.startsWith('/assets/'))return stream(join(root,'public',url.pathname.slice(8)),res);const safe=normalize(url.pathname).replace(/^(\.\.[/\\])+/,'');let target=join(root,safe);if(url.pathname==='/')target=join(root,'index.html');else if(existsSync(target)&&statSync(target).isDirectory())target=join(target,'index.html');else if(!extname(target))target=join(root,safe,'index.html');if(!existsSync(target)||!statSync(target).isFile()){res.writeHead(404);return res.end('Not found')}if(extname(target)==='.html'){let html=await readFile(target,'utf8');html=html.replace(/href=(['"])https:\/\/getwificode\.com\//gi,'href=$1/');if(!html.includes('/assets/tracker.js'))html=html.replace(/<\/body>/i,'<script src="/assets/tracker.js" defer></script></body>');res.writeHead(200,{'content-type':types['.html'],'cache-control':'no-cache'});return res.end(html)}return stream(target,res)}catch(error){console.error(error);return json(res,500,{error:'Server error'})}}

createServer(handler).listen(port,()=>console.log(`WifiCode: http://localhost:${port} | Admin: http://localhost:${port}/admin`));
setInterval(()=>processDueMessages().catch(console.error),15000).unref();processDueMessages().catch(console.error);
