import { createReadStream, existsSync, statSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { extname, join, normalize } from 'node:path';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { upsertLead, addEvent, scheduleAutomations, one, many, run, ready } from './lib/database.mjs';
import { processDueMessages } from './lib/automation.mjs';
import { getProduct } from './lib/products.mjs';
import { chargeOpaque, chargeProfile } from './lib/authorize-net.mjs';

const root=process.cwd(),port=Number(process.env.PORT||4173),now=()=>new Date().toISOString();
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const json=(res,status,value)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(value));};
const csvCell=value=>{let text=value==null?'':String(value);if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`};
const secureEqual=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&timingSafeEqual(x,y)};
const adminOk=req=>{const[kind,token='']=(req.headers.authorization||'').split(' ');if(kind!=='Basic')return false;const[user,password]=Buffer.from(token,'base64').toString().split(':');return secureEqual(user,process.env.ADMIN_USER||'admin')&&secureEqual(password,process.env.ADMIN_PASSWORD||'change-me')};
const requireAdmin=(req,res)=>{if(adminOk(req))return true;res.writeHead(401,{'www-authenticate':'Basic realm="WifiCode Admin"'});res.end('Authentication required');return false};
const sessionSecret=()=>process.env.SESSION_SECRET||'';
const sign=value=>createHmac('sha256',sessionSecret()).update(value).digest('base64url');
const makeSession=leadId=>{const value=Buffer.from(JSON.stringify({leadId:Number(leadId),created:Date.now()})).toString('base64url');return `${value}.${sign(value)}`};
const readSession=req=>{try{const cookie=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('wc_session='));if(!cookie||!sessionSecret())return null;const token=decodeURIComponent(cookie.slice(11)),[value,signature]=token.split('.');if(!secureEqual(signature,sign(value)))return null;const session=JSON.parse(Buffer.from(value,'base64url').toString());return Date.now()-session.created<86400000?session:null}catch{return null}};
const setSession=(req,res,leadId)=>{const secure=(req.headers['x-forwarded-proto']==='https'||process.env.APP_URL?.startsWith('https://'))?'; Secure':'';res.setHeader('set-cookie',`wc_session=${encodeURIComponent(makeSession(leadId))}; Path=/; HttpOnly; SameSite=Lax; Max-Age=86400${secure}`)};

async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>1e6)throw Error('Request too large');chunks.push(chunk)}const raw=Buffer.concat(chunks).toString(),type=req.headers['content-type']||'';return type.includes('application/json')?(raw?JSON.parse(raw):{}):Object.fromEntries(new URLSearchParams(raw))}
function stream(file,res){if(!existsSync(file)){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':types[extname(file).toLowerCase()]||'application/octet-stream','cache-control':'no-cache'});createReadStream(file).pipe(res)}

async function api(req,res,url){
  if(req.method==='GET'&&url.pathname==='/api/checkout/config'){try{const product=getProduct(url.searchParams.get('product')||'front');return json(res,200,{apiLoginId:process.env.AUTHORIZE_NET_API_LOGIN_ID,publicClientKey:process.env.AUTHORIZE_NET_PUBLIC_CLIENT_KEY,environment:process.env.AUTHORIZE_NET_ENV,product:{id:product.id,name:product.name,formatted:`$${product.amount.toFixed(2)}`}})}catch(error){return json(res,400,{error:error.message})}}
  if(req.method==='POST'&&url.pathname==='/api/checkout'){const input=await body(req);if(!input.consent)return json(res,400,{error:'Payment authorization is required'});let product;try{product=getProduct(input.product)}catch(error){return json(res,400,{error:error.message})}if(product.id!=='front')return json(res,400,{error:'Initial checkout product is invalid'});const result=await upsertLead({...input,source:'checkout',email_consent:false,sms_consent:false});const lead=result.lead;let order=await one('SELECT * FROM orders WHERE lead_id=$1 AND product_id=$2',[lead.id,product.id]);if(order?.status==='paid'){setSession(req,res,lead.id);return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)})}const stamp=now();if(order){await run("UPDATE orders SET status='pending',response_message='',updated_at=$1 WHERE id=$2",[stamp,order.id])}else{order=(await run('INSERT INTO orders(lead_id,product_id,product_name,amount,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$6) RETURNING id',[lead.id,product.id,product.name,product.amount,'pending',stamp]))[0]}try{const payment=await chargeOpaque({product,opaqueData:input.opaqueData,customer:input,invoice:`WC-${order.id}`});await run("UPDATE orders SET status='paid',transaction_id=$1,response_code=$2,response_message='Approved',updated_at=$3 WHERE id=$4",[payment.transactionId,payment.responseCode,now(),order.id]);if(payment.customerProfileId&&payment.paymentProfileId)await run(`INSERT INTO gateway_profiles(lead_id,customer_profile_id,payment_profile_id,created_at,updated_at) VALUES($1,$2,$3,$4,$4) ON CONFLICT(lead_id) DO UPDATE SET customer_profile_id=excluded.customer_profile_id,payment_profile_id=excluded.payment_profile_id,updated_at=excluded.updated_at`,[lead.id,payment.customerProfileId,payment.paymentProfileId,now()]);await addEvent(lead.id,'sale',{value:product.amount,currency:'USD',product_id:product.id,transaction_id:payment.transactionId,metadata:{gateway:'authorize_net'}});await scheduleAutomations(lead,'conversion');setSession(req,res,lead.id);return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)})}catch(error){await run("UPDATE orders SET status='declined',response_code=$1,response_message=$2,updated_at=$3 WHERE id=$4",[error.code||'',String(error.message).slice(0,500),now(),order.id]);return json(res,402,{error:error.message})}}
  if(req.method==='POST'&&url.pathname==='/api/purchase'){const session=readSession(req);if(!session)return json(res,401,{error:'Your secure checkout session expired. Please complete the initial checkout again.'});const input=await body(req);let product;try{product=getProduct(input.product)}catch(error){return json(res,400,{error:error.message})}if(product.id==='front')return json(res,400,{error:'Invalid upgrade'});const lead=await one('SELECT * FROM leads WHERE id=$1',[session.leadId]),profile=await one('SELECT * FROM gateway_profiles WHERE lead_id=$1',[session.leadId]);if(!lead||!profile)return json(res,409,{error:'Saved payment profile is unavailable. Please contact support.'});let order=await one('SELECT * FROM orders WHERE lead_id=$1 AND product_id=$2',[lead.id,product.id]);if(order?.status==='paid')return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)});const stamp=now();if(order){await run("UPDATE orders SET status='pending',response_message='',updated_at=$1 WHERE id=$2",[stamp,order.id])}else{order=(await run('INSERT INTO orders(lead_id,product_id,product_name,amount,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$6) RETURNING id',[lead.id,product.id,product.name,product.amount,'pending',stamp]))[0]}try{const payment=await chargeProfile({product,customerProfileId:profile.customer_profile_id,paymentProfileId:profile.payment_profile_id,invoice:`WC-${order.id}`});await run("UPDATE orders SET status='paid',transaction_id=$1,response_code=$2,response_message='Approved',updated_at=$3 WHERE id=$4",[payment.transactionId,payment.responseCode,now(),order.id]);await addEvent(lead.id,'sale',{value:product.amount,currency:'USD',product_id:product.id,transaction_id:payment.transactionId,metadata:{gateway:'authorize_net',one_click:true}});return json(res,200,{ok:true,next:product.next,orderId:Number(order.id)})}catch(error){await run("UPDATE orders SET status='declined',response_code=$1,response_message=$2,updated_at=$3 WHERE id=$4",[error.code||'',String(error.message).slice(0,500),now(),order.id]);return json(res,402,{error:error.message})}}
  if(req.method==='POST'&&url.pathname==='/api/leads'){const input=await body(req);input.ip=req.headers['x-forwarded-for']?.split(',')[0]||req.socket.remoteAddress||'';const result=await upsertLead(input);await addEvent(result.lead.id,'opt_in',{page:input.landing_page,metadata:{source:input.source||'website'}});if(result.created)await scheduleAutomations(result.lead);return json(res,201,{ok:true,id:Number(result.lead.id)})}
  if(req.method==='POST'&&url.pathname==='/api/events'){const input=await body(req),allowed=new Set(['page_view','checkout_click']);if(!allowed.has(input.type))return json(res,400,{error:'Unsupported event'});await addEvent(null,input.type,{page:input.page,product_id:input.product_id,metadata:{aid:input.aid,tid:input.tid,utm_source:input.utm_source,utm_campaign:input.utm_campaign}});return json(res,201,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/webhooks/jvzoo'){const supplied=url.searchParams.get('secret')||req.headers['x-webhook-secret'];if(!process.env.WEBHOOK_SECRET||!secureEqual(supplied,process.env.WEBHOOK_SECRET))return json(res,401,{error:'Invalid webhook secret'});const input=await body(req),email=input.ccustemail||input.email,name=input.ccustname||input.name||'';const result=await upsertLead({email,phone:input.ccustphone||input.phone,name,source:'jvzoo',aid:input.caffitid||input.aid,tid:input.ctid||input.tid});const raw=String(input.ctransaction||input.transaction_type||input.type||'sale').toLowerCase(),eventType=raw.includes('refund')||raw.includes('cancel')?'refund':'sale';const added=await addEvent(result.lead.id,eventType,{value:input.camount||input.amount||input.ctransamount,currency:input.ccurrency||'USD',product_id:input.cproditem||input.product_id,transaction_id:input.ctransreceipt||input.transaction_id,metadata:input});if(added&&eventType==='sale')await scheduleAutomations(result.lead,'conversion');return json(res,200,{ok:true})}
  if(url.pathname.startsWith('/api/admin/')){
    if(req.method==='GET'&&url.pathname==='/api/admin/leads/export'){const items=await many("SELECT l.*,CASE WHEN EXISTS(SELECT 1 FROM orders o WHERE o.lead_id=l.id AND o.status='paid') THEN 'customer' ELSE l.status END AS display_status FROM leads l ORDER BY l.created_at DESC"),columns=[['ID','id'],['First Name','first_name'],['Last Name','last_name'],['Email','email'],['Phone','phone'],['Status','display_status'],['Source','source'],['Tags','tags'],['Notes','notes'],['Email Consent','email_consent'],['SMS Consent','sms_consent'],['Unsubscribed','unsubscribed'],['AID','aid'],['TID','tid'],['UTM Source','utm_source'],['UTM Campaign','utm_campaign'],['Landing Page','landing_page'],['Created','created_at'],['Updated','updated_at']],csv='\uFEFF'+[columns.map(([label])=>csvCell(label)).join(','),...items.map(item=>columns.map(([,key])=>csvCell(item[key])).join(','))].join('\r\n');res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="wificode-leads-${now().slice(0,10)}.csv"`,'cache-control':'no-store'});return res.end(csv)}
    if(req.method==='GET'&&url.pathname==='/api/admin/orders'){const pageSize=50,total=Number((await one('SELECT COUNT(*) AS total FROM orders')).total),pages=Math.max(1,Math.ceil(total/pageSize)),page=Math.min(pages,Math.max(1,Number(url.searchParams.get('page'))||1)),offset=(page-1)*pageSize,items=await many('SELECT o.*,l.email,l.phone,l.first_name,l.last_name FROM orders o JOIN leads l ON l.id=o.lead_id ORDER BY o.updated_at DESC LIMIT $1 OFFSET $2',[pageSize,offset]);return json(res,200,{items,pagination:{page,pageSize,total,pages}})}
    if(req.method==='GET'&&url.pathname==='/api/admin/sales'){const pageSize=50,total=Number((await one("SELECT COUNT(DISTINCT lead_id) AS total FROM orders WHERE status='paid'")).total),pages=Math.max(1,Math.ceil(total/pageSize)),page=Math.min(pages,Math.max(1,Number(url.searchParams.get('page'))||1)),offset=(page-1)*pageSize,items=await many(`SELECT l.id,l.first_name,l.last_name,l.email,l.phone,COUNT(o.id)::int purchase_count,COALESCE(SUM(o.amount),0) gross_sales,STRING_AGG(o.product_name, ', ' ORDER BY o.created_at) products,MIN(o.created_at) first_purchase_at,MAX(o.updated_at) last_purchase_at,COALESCE(r.refund_count,0)::int refund_count,COALESCE(r.refund_amount,0) refund_amount,COALESCE(SUM(o.amount),0)-COALESCE(r.refund_amount,0) net_sales FROM leads l JOIN orders o ON o.lead_id=l.id AND o.status='paid' LEFT JOIN (SELECT lead_id,COUNT(*) refund_count,COALESCE(SUM(value),0) refund_amount FROM events WHERE type='refund' GROUP BY lead_id) r ON r.lead_id=l.id GROUP BY l.id,l.first_name,l.last_name,l.email,l.phone,r.refund_count,r.refund_amount ORDER BY MAX(o.updated_at) DESC LIMIT $1 OFFSET $2`,[pageSize,offset]);return json(res,200,{items,pagination:{page,pageSize,total,pages}})}
    if(req.method==='GET'&&url.pathname==='/api/admin/leads'){const page=Math.max(1,Number(url.searchParams.get('page'))||1),pageSize=Math.min(100,Math.max(10,Number(url.searchParams.get('pageSize'))||25)),offset=(page-1)*pageSize,total=Number((await one('SELECT COUNT(*) AS total FROM leads')).total),items=await many("SELECT l.*,CASE WHEN EXISTS(SELECT 1 FROM orders o WHERE o.lead_id=l.id AND o.status='paid') THEN 'customer' ELSE l.status END AS display_status FROM leads l ORDER BY l.created_at DESC LIMIT $1 OFFSET $2",[pageSize,offset]);return json(res,200,{items,pagination:{page,pageSize,total,pages:Math.max(1,Math.ceil(total/pageSize))}})}
    if(req.method==='GET'&&url.pathname==='/api/admin/dashboard'){const counts=await one("SELECT (SELECT COUNT(*) FROM leads) leads,(SELECT COUNT(DISTINCT lead_id) FROM orders WHERE status='paid') buyers,(SELECT COUNT(*) FROM orders) attempts,(SELECT COUNT(*) FROM orders WHERE status='declined') declined,(SELECT COALESCE(SUM(amount),0) FROM orders WHERE status='paid') revenue,(SELECT COUNT(*) FROM events WHERE type='page_view') page_views"),leads=Number(counts.leads),buyers=Number(counts.buyers),revenue=Number(counts.revenue);return json(res,200,{updatedAt:now(),stats:{leads,buyers,attempts:Number(counts.attempts),declined:Number(counts.declined),revenue,pageViews:Number(counts.page_views),rate:leads?((buyers/leads)*100).toFixed(1):'0.0'},leads:await many("SELECT l.*,CASE WHEN EXISTS(SELECT 1 FROM orders o WHERE o.lead_id=l.id AND o.status='paid') THEN 'customer' ELSE l.status END AS display_status FROM leads l ORDER BY l.created_at DESC LIMIT 250"),orders:await many("SELECT o.*,l.email,l.phone,l.first_name,l.last_name FROM orders o JOIN leads l ON l.id=o.lead_id ORDER BY o.updated_at DESC LIMIT 250"),automations:await many('SELECT * FROM automations ORDER BY created_at DESC'),messages:await many('SELECT * FROM messages ORDER BY created_at DESC LIMIT 100')})}
    if(req.method==='POST'&&url.pathname==='/api/admin/leads'){const input=await body(req);input.source='admin';const result=await upsertLead(input);await addEvent(result.lead.id,'opt_in',{metadata:{source:'admin'}});if(result.created)await scheduleAutomations(result.lead);return json(res,201,{ok:true,id:Number(result.lead.id)})}
    if(req.method==='POST'&&url.pathname==='/api/admin/automations'){const input=await body(req);if(!['email','sms'].includes(input.channel))return json(res,400,{error:'Invalid channel'});const stamp=now();if(input.id)await run('UPDATE automations SET name=$1,channel=$2,delay_minutes=$3,subject=$4,message=$5,enabled=$6,updated_at=$7 WHERE id=$8',[input.name,input.channel,Number(input.delay_minutes),input.subject||'',input.message,Boolean(input.enabled),stamp,input.id]);else await run('INSERT INTO automations(name,channel,delay_minutes,subject,message,enabled,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$7)',[input.name,input.channel,Number(input.delay_minutes),input.subject||'',input.message,Boolean(input.enabled),stamp]);return json(res,201,{ok:true})}
  }
  return json(res,404,{error:'Not found'})
}

export async function handler(req,res){try{let url=new URL(req.url,`http://${req.headers.host||'localhost'}`);const rewrittenPath=url.searchParams.get('__path');if(rewrittenPath){url=new URL(rewrittenPath,`http://${req.headers.host||'localhost'}`);for(const[key,value]of new URL(req.url,`http://${req.headers.host||'localhost'}`).searchParams)if(key!=='__path')url.searchParams.append(key,value)}if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(url.pathname==='/checkout')return stream(join(root,'public','checkout.html'),res);if(url.pathname==='/admin'||url.pathname==='/admin/')return stream(join(root,'public','admin.html'),res);if(url.pathname.startsWith('/assets/'))return stream(join(root,'public',url.pathname.slice(8)),res);const safe=normalize(url.pathname).replace(/^(\.\.[/\\])+/,'');let target=join(root,safe);if(url.pathname==='/')target=join(root,'index.html');else if(existsSync(target)&&statSync(target).isDirectory())target=join(target,'index.html');else if(!extname(target))target=join(root,safe,'index.html');if(!existsSync(target)||!statSync(target).isFile()){res.writeHead(404);return res.end('Not found')}if(extname(target)==='.html'){let html=await readFile(target,'utf8');html=html.replace(/href=(['"])https:\/\/getwificode\.com\//gi,'href=$1/');if(!html.includes('/assets/tracker.js'))html=html.replace(/<\/body>/i,'<script src="/assets/tracker.js" defer></script></body>');res.writeHead(200,{'content-type':types['.html'],'cache-control':'no-cache'});return res.end(html)}return stream(target,res)}catch(error){console.error(error);return json(res,500,{error:'Server error'})}}

export default handler;

if(!process.env.VERCEL){createServer(handler).listen(port,()=>console.log(`WifiCode: http://localhost:${port} | Admin: http://localhost:${port}/admin`));setInterval(()=>processDueMessages().catch(console.error),15000).unref();processDueMessages().catch(console.error)}
